Create lab1
VGP125SummerTerm2024/DunkHunt2024 pull request #29
Opened 2024-07-22 21:29 UTC by Will-LaBo

2024-07-22 21:47 UTC, dtranTFS commented
Make sure you tag the Git Master reviewers or this wont ever get merged in. If your not sure have a look on Trello and also ask your classmates for help

2024-07-22 21:48 UTC, dtranTFS requested changes
Add Git Master Reviewers

2024-07-22 21:50 UTC, Will-LaBo commented on Assignment/lab1
@Lvl100Wizard

2024-07-22 21:50 UTC, Will-LaBo commented on Assignment/lab1
@Lvl100Wizard @

2024-07-22 21:50 UTC, Lvl100Wizard approved these changes

2024-07-22 21:54 UTC, Lvl100Wizard commented
Hey William, could you add me as a reviewer and also rename your file to your first name + last name, this is what Mr Tran wants for A1. Cheers

2024-07-24 13:44 UTC, slamdunkaroo approved these changes

2024-07-24 13:44 UTC, slamdunkaroo approved these changes

2024-07-24 21:22 UTC, slamdunkaroo approved these changes

2024-07-24 21:22 UTC, slamdunkaroo approved these changes

2024-07-26 11:42 UTC, slamdunkaroo approved these changes

2024-07-26 23:09 UTC, dtranTFS approved these changes

2024-07-26 23:09 UTC, merged